# jfu Configuration File

# Source directory containing your Java files
src_dir = "./test"

# Output directory for compiled .class files
out_dir = "./out"

# Location of the build cache file
cache_file = "./jfu-cache.json"

# JVM options to pass when running your program
jvm_opts = ["-Xmx256m"]
